version: '2.1'

orbs:
  node: circleci/node@5.0.2

jobs:
  ci:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.16.0'
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run type-check
          name: Type Check
      - run:
          command: yarn build
          name: Build
