export const ENV = {
  FATHER_OF_THE_BRIDE: process.env.NEXT_PUBLIC_FATHER_OF_THE_BRIDE,
  MOTHER_OF_THE_BRIDE: process.env.NEXT_PUBLIC_MOTHER_OF_THE_BRIDE,
  FATHER_OF_THE_GROOM: process.env.NEXT_PUBLIC_FATHER_OF_THE_GROOM,
  MOTHER_OF_THE_GROOM: process.env.NEXT_PUBLIC_MOTHER_OF_THE_GROOM,
  BRIDE: process.env.NEXT_PUBLIC_BRIDE,
  GROOM: process.env.NEXT_PUBLIC_GROOM,
  TIME: process.env.NEXT_PUBLIC_TIME,
  PLACE: process.env.NEXT_PUBLIC_PLACE,
  PLACE_LAT: process.env.NEXT_PUBLIC_PLACE_LAT,
  PLACE_LNG: process.env.NEXT_PUBLIC_PLACE_LNG,
  KAKAO_KEY: process.env.NEXT_PUBLIC_KAKAO_KEY,
};
